"""initial_migration_with_processed_files

Revision ID: 67371aeb5ae0
Revises: 
Create Date: 2025-11-04 13:24:09.349333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67371aeb5ae0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'ERROR', name='ingestionstatus'), nullable=True),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('source_file_pattern', sa.String(), nullable=True),
    sa.Column('source_credentials', sa.JSON(), nullable=True),
    sa.Column('format_type', sa.String(), nullable=False),
    sa.Column('format_options', sa.JSON(), nullable=True),
    sa.Column('schema_inference', sa.String(), nullable=True),
    sa.Column('schema_evolution_enabled', sa.Boolean(), nullable=True),
    sa.Column('schema_json', sa.JSON(), nullable=True),
    sa.Column('destination_catalog', sa.String(), nullable=False),
    sa.Column('destination_database', sa.String(), nullable=False),
    sa.Column('destination_table', sa.String(), nullable=False),
    sa.Column('write_mode', sa.String(), nullable=True),
    sa.Column('partitioning_enabled', sa.Boolean(), nullable=True),
    sa.Column('partitioning_columns', sa.JSON(), nullable=True),
    sa.Column('z_ordering_enabled', sa.Boolean(), nullable=True),
    sa.Column('z_ordering_columns', sa.JSON(), nullable=True),
    sa.Column('schedule_frequency', sa.String(), nullable=True),
    sa.Column('schedule_time', sa.String(), nullable=True),
    sa.Column('schedule_timezone', sa.String(), nullable=True),
    sa.Column('schedule_cron', sa.String(), nullable=True),
    sa.Column('backfill_enabled', sa.Boolean(), nullable=True),
    sa.Column('backfill_start_date', sa.DateTime(), nullable=True),
    sa.Column('row_count_threshold', sa.Integer(), nullable=True),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=True),
    sa.Column('alert_recipients', sa.JSON(), nullable=True),
    sa.Column('checkpoint_location', sa.String(), nullable=False),
    sa.Column('last_run_id', sa.String(), nullable=True),
    sa.Column('last_run_time', sa.DateTime(), nullable=True),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('estimated_monthly_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestions_id'), 'ingestions', ['id'], unique=False)
    op.create_index(op.f('ix_ingestions_tenant_id'), 'ingestions', ['tenant_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingestion_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', name='runstatus'), nullable=True),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('files_processed', sa.Integer(), nullable=True),
    sa.Column('records_ingested', sa.Integer(), nullable=True),
    sa.Column('bytes_read', sa.Integer(), nullable=True),
    sa.Column('bytes_written', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('spark_job_id', sa.String(), nullable=True),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_id'), 'runs', ['id'], unique=False)
    op.create_index(op.f('ix_runs_ingestion_id'), 'runs', ['ingestion_id'], unique=False)
    op.create_table('schema_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ingestion_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('affected_files', sa.JSON(), nullable=True),
    sa.Column('resolution_type', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_versions_id'), 'schema_versions', ['id'], unique=False)
    op.create_index(op.f('ix_schema_versions_ingestion_id'), 'schema_versions', ['ingestion_id'], unique=False)
    op.create_table('processed_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ingestion_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_etag', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_ingested', sa.Integer(), nullable=True),
    sa.Column('bytes_read', sa.BigInteger(), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processed_files_ingestion_status', 'processed_files', ['ingestion_id', 'status'], unique=False)
    op.create_index('idx_processed_files_path', 'processed_files', ['file_path'], unique=False)
    op.create_index('idx_processed_files_run', 'processed_files', ['run_id'], unique=False)
    op.create_index('idx_processed_files_status_date', 'processed_files', ['status', 'processed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_processed_files_status_date', table_name='processed_files')
    op.drop_index('idx_processed_files_run', table_name='processed_files')
    op.drop_index('idx_processed_files_path', table_name='processed_files')
    op.drop_index('idx_processed_files_ingestion_status', table_name='processed_files')
    op.drop_table('processed_files')
    op.drop_index(op.f('ix_schema_versions_ingestion_id'), table_name='schema_versions')
    op.drop_index(op.f('ix_schema_versions_id'), table_name='schema_versions')
    op.drop_table('schema_versions')
    op.drop_index(op.f('ix_runs_ingestion_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_ingestions_tenant_id'), table_name='ingestions')
    op.drop_index(op.f('ix_ingestions_id'), table_name='ingestions')
    op.drop_table('ingestions')
    # ### end Alembic commands ###
